### PR TITLE
Cheese Cube sound scheme by Seediffusion

### PR DESCRIPTION
**Pull request by seediffusion**

### CODE REVIEW

**Comment by ORelio** [comment]
Hi,
Thanks for contributing to the Sound Scheme repository!
Your sound scheme sounds very good, nice job!

Currently, your sound scheme has no image or description:

image

I could edit it like so if you're okay with it:

image

If you prefer to merge as is, let me know.

**Comment by seediffusion** [comment]
If a description is required, I'll gladly add one. I didn't add an image since I'm totally blind and it doesn't make much sense to me to add an image to a sound scheme.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ORelio** [comment]
Hi,
Don't worry, they are not mandatory, so let's forget the image (I had set a picture of a cheese cube in my example).
I see that you have a dedicated repository: https://github.com/seediffusion/CubeSuite
If you wish, it can be set as description for your sound scheme.
Then again, I'm just providing feedback, I can merge your pull request without any changes if you prefer.

**Comment by seediffusion** [comment]
Feel free to include the cheese cube image and merge. :)
As an aside, I filed an issue on the main Sound Manager repo. I wanted to get in touch with you personally, but wasn't sure how to do it, as I generally prefer to do that rather than submit GitHub issues. That and the readme doesn't include build/compile instructions.er than

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ORelio** [comment]
Okay, I'll make the changes when I get back to my computer.

I have missed the notification for your issue on the main repository, sorry, I'll make sure to address it as well.

You can build the project using Visual Studio or MSBuild tool, I'll try to add more info when I have spare time to improve the Readme.

-------- Message d'origine --------

**Comment by seediffusion** [comment]
Which version of VS?

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ORelio** [comment]
Hi,

I've made the discussed changes and merged the PR, your sound scheme is now available to download for every SoundManager user 🙂 

Regarding your other question:

1. Visual Studio
    a. I'm using Visual Studio 2010 to compile SoundManager in order to maintain compatibility with old Windows versions. The corresponding free version should be Visual C# 2010 Express
    b. If you don't mind compiling without support for old Windows Versions, you should be able to load the project under Visual Studio Community (any recent version) then accept the upgrade to a newer .NET framework target version when opening the project. From there you can compile, the build shortcut should be F6.

2. MSBuild
    a. MSBuild should come pre-installed on any recent Windows version
    b. locate msbuild.exe for .NET 4, it should be inside `C:\Windows\Microsoft.NET\Framework64\v4.0.30319` but the last digits in the folder name may vary on your setup
    c. in a console open in that folder, run `msbuild.exe C:\path\to\SoundManager.csproj`
    d. if built correctly, the executable should be under `bin\Debug` folders in the same folder as `SoundManager.csproj`

**Comment by seediffusion** [comment]
When I try to build Sound Manager with Visual Studio 2010, with all VS2010 updates installed, I get this.
[SMErrors.txt](https://github.com/user-attachments/files/15880547/SMErrors.txt)

**Comment by seediffusion** [comment]
Is there a way to clear the sound scheme downloader's cache?

**Comment by ORelio** [comment]
The sound scheme downloader stores the sound files directly into the `Schemes` folder next to SoundManager.exe, (in install mode, the folder is named `SoundManager` under in My Music).

The download program retrieves the list of sound schemes using the GitHub API, which is rate limited. To avoir hitting the rate limit, it creates a `sound-manager-schemes.txt` file into the `%temp%` directory. This file is valid for 1 hour, but you can delete it and reload the downloader if you wish to refresh the list immediately.

There are no other cache files in the downloader.

**Pull request merged**
