### PR TITLE
Added some sound Schemes, especially some sound schemes bassed on old versions of Windows, other schemes and some schemes created by myself

### PR DESCRIPTION
**Pull request by Sergiaws**
Some of these sound schemes lack some sounds, since you didn't implemented a lot of necesary events to make work such schemes as there where shiped in their original Windows. Since noone would like all of these sound schemes, I would suggest to split the sound schemes into categories an maybe update the installer so you could choose your favorite schemes bassed into the categories. Some necesary events are email notification sounds, battery related, open/close an application and menu related events such as maximize, minimize, etc. Adding these events would make possible to create more interesting schemes, such as Mac scheme, improve schemes bassed on older Windows/Windows CE or create/improve more complex Linux bassed schemes.

### CODE REVIEW

**Comment by ORelio** [comment]
Hi,
Thanks for contributing so many schemes! I'll look into this immediately.
You're right about the sound events, I was busy when you opened #3 and forgot about it.
I'll try again to look into this.

**Comment by ORelio** [comment]
OK so here is some feedback about the schemes:

* File naming: In the repository, all schemes have no spaces or quotes. I'll suggest file names below.
* For schemes that have missing sound, how about copying another sound? Details below.
* Most schemes do not have a cover image. I'll try to suggest some below.

You may agree or not with my suggestions. If you don't, I'll add the schemes as is (just renaming them for sorting and fixing the issues in **bold** below), but if you do, you can update your repository before I merge the changes:

### `Andre Louis's Sound Scheme.ths`
* Suggested file name: `Andre-Louis-44.1K`
* Suggested display name: `Andre Louis 44.1.K` ([source](https://twitter.com/FreakyFwoof/status/1549271081793601537))
* Suggested About URL: `https://twitter.com/FreakyFwoof`
* Suggested Admin Access sound: Warning.wav

### `Nokia old.ths`
* Missing sounds that might be nice to populate: USB Connect/Remove/Error, Admin Access
* Suggested file name: `Nokia-Old.ths`
* Suggested icon:
nokia

### `Ubuntu classic.ths`
* Missing sounds that might be nice to populate: Recycle Bin, Admin Access
* Suggested file name: `Linux-Ubuntu-18.04.ths`
* Suggested Name: `Ubutnu 18.04`
* Suggested icon:
ubuntu

### `Ubuntu newer.ths`
* Missing sounds that might be nice to populate: Shutdown, Log Off, Admin Access
* Other missing sounds, not very important: USB Error, Navigate
* Suggested file name: `Linux-Ubuntu-20.04.ths`
* Suggested Name: `Ubuntu 20.04` (in case they change again, it will be easy to name the new one)
* Suggested icon:
ubuntu-icon

### `Windos Vista Tinker.ths`
* Sound event Information has a slight delay before playing. Could be nice to edit it out, but could also be nice to keep it for preservation if that's an official .wav file from Microsoft.
* Suggested file name: `Windows-Vista-Tinker.ths`wind
* Suggested Name: Tinker
* Suggested icon (used for Vista Pearl and Glass):
Scheme

### `Windows 10 build 10074.ths`
* Do you know why this build has different sounds from the others?
* Suggested file name: `Windows-10-build-10074.ths`

### `Windows 2000-ME.ths`
* Missing sounds that might be nice to populate: Balloon, Admin Access
* Suggested file name: `Windows-2000-ME.ths`

### `Windows 7-8 consumer and release preview mix.ths`
* Suggested file name: `Windows-7-8-RP-Mix.ths`

### `Windows 8-10-11 remix.ths`
* Suggested file name: `Windows-8-10-Mix.ths`
* Suggested author: `Microsoft Corporation / Sergiaws`
* Suggested icon: (taken from Windows-8-10-Mix)
Scheme

### `Windows 98 Plus! Architecture.ths`
* Missing sounds that might be copied from default Windows 98 or 2000 sounds: USB Connect/Remove/Error, Balloon, Navigate
* Other missing sounds: Question (might be copied from Information), Admin Access (might be copied from Warning)
* Suggested file name: `Windows-98-Plus-Architecture.ths`
* Suggested icon:
Win98Plus

### `Windows 98 Plus! Geometry.ths`
* Missing sounds that might be copied from default Windows 98 or 2000 sounds: USB Connect/Remove/Error, Balloon, Navigate
* Other missing sounds: Admin Access (might be copied from Warning)
* Suggested file name: `Windows-98-Plus-Geometry.ths`
* Suggested icon:
Win98Plus

### `Windows 98 Plus! Jazz.ths`
* Missing sounds that might be copied from default Windows 98 or 2000 sounds: USB Connect/Remove/Error, Balloon, Navigate
* Other missing sounds: Admin Access (might be copied from Warning)
* Suggested file name: `Windows-98-Plus-Jazz.ths`
* Suggested icon:
Win98Plus

### `Windows 98 Plus! Science fiction.ths`
* Missing sounds that might be copied from default Windows 98 or 2000 sounds: USB Connect/Remove/Error, Balloon, Navigate
* Other missing sounds: Admin Access (might be copied from Warning)
* Suggested file name: `Windows-98-Plus-Science-Fiction.ths`
* Suggested icon:
Win98Plus

### `Windows 98 plus! Windows 98.ths`
* Missing sounds that might be copied from default Windows 98 or 2000 sounds: USB Connect/Remove/Error, Navigate
* Other missing sounds: Admin Access (might be copied from Warning)
* Suggested file name: `Windows-98-Plus.ths`
* Suggested Name: `Windows 98 Plus!`
* Suggested icon:
Win98Plus

### `Windows 98 plus! World Traveller.ths`
* Missing sounds that might be copied from default Windows 98 or 2000 sounds: USB Connect/Remove/Error, Balloon, Navigate
* **Leftover Admin Access sound from Windows 7 (should be removed,** might be replaced by Warning.wav)
* Suggested file name: `Windows-98-Plus-World-Traveller.ths`
* Suggested icon:
Win98Plus

### `Windows 98 plus! beta sound scheme.ths`
* Missing sounds that might be copied from default Windows 98 or 2000 sounds: USB Connect/Remove/Error, Navigate
* Other missing sounds: Admin Access (might be copied from Warning)
* Suggested file name: `Windows-98-Plus-Beta.ths`
* Suggested icon:
Win98Plus

### `Windows 9x underwater.ths`
* Missing sounds that might be copied from default Windows 98 or 2000 sounds: USB Connect/Remove/Error, Navigate
* Other missing sounds: Admin Access (might be copied from Warning)
* Suggested file name: `Windows-9x-Underwater.ths`
* Suggested Name: `Underwater`
* Suggested icon:
win98

### `Windows 9x-2000 Utopia.ths`
* Missing sounds that might be copied from default Windows 98 or 2000 sounds: Log On, Log Off, USB Connect/Remove/Error, Navigate
* Other missing sounds: Admin Access (might be copied from Warning)
* Suggested file name: `Windows-9x-2000-Utopia.ths`
* Suggested Name: `Utopia`
* Suggested icon:
win98

### `Windows 9x-2000 remix.ths`
* Laughed at the sound events played on a recorder. Seems worth making a full scheme with that idea xD
* Sound "Question" seems too long. Consider using a shorter sound for this event.
* Suggested file name: `Windows-9x-2000-Mix.ths`
* Suggested author: `Microsoft Corporation / Sergiaws`
* Suggested icon:
win98

### `Windows Beta sounds.ths`
* Suggested file name: `Windows-Beta-Mix.ths`
* Suggested Name: `Windows Beta Sound Mix`
* Suggested author: `Microsoft Corporation / Sergiaws`
* Suggested icon: (current one is from Windows 10, which seems too recent)
Scheme

### `Windows CE Analogue.ths`
* Missing sounds that might be nice to add: Shutdown, Log On, Log Off, Balloon, Navigate
* Other missing sounds: Admin Access (might be copied from Warning)
* Suggested file name: `Windows-CE-Analogue.ths`
* Suggested icon:
Scheme

### `Windows CE Metallic.ths`
* Missing sounds that might be nice to add: Shutdown, Log On, Log Off, Balloon, Navigate
* Other missing sounds: Admin Access (might be copied from Warning)
* Suggested file name: `Windows-CE-Metallic.ths`
* Suggested icon:
Scheme

### `Windows CE Organic.ths`
* Missing sounds that might be nice to add: Shutdown, Log On, Log Off, Balloon, Navigate
* Other missing sounds: Admin Access (might be copied from Warning)
* Suggested file name: `Windows-CE-Organic.ths`
* Suggested icon:
Scheme

### `Windows CE Pocket PC 2000.ths`
* **Leftover USB Error sound from The-Simpsons-FR.ths (should be replaced by the correct one)**
* Missing sounds that might be nice to add: Shutdown, Log On, Log Off, Balloon, Navigate
* Other missing sounds: Admin Access (might be copied from Warning)
* Suggested file name: `Windows-CE-Pocket-PC-2000.ths`
* Suggested Name: `Windows CE Pocket PC 2002 Default`
* Suggested icon:
Windows2000

### `Windows CE UI Set.ths`
* Missing sounds that might be nice to add: Balloon, Navigate
* Other missing sounds: Admin Access (might be copied from Warning)
* Suggested file name: `Windows-CE-UI-Set.ths`
* Suggested icon:
Scheme

### `Windows Movile 5.0 & XP.ths`
* Suggested file name; `Windows-Mobile-5.0-XP.ths`
* Suggested name: `Windows Mobile 5.0-XP`

### `Windows NT 4 Resource Pack Ancient Pathways.ths`
* Missing sounds that might be copied from default Windows 98 or 2000 sounds: USB Connect/Remove/Error, Balloon, Navigate, Recycle Bin
* Other missing sounds: Admin Access (might be copied from Warning)
* Suggested file name: `Windows-NT4-Ancient-Pathways.ths`
* Suggested icon:
Scheme

### `Windows Pocket PC 2000.ths`
* Missing sounds that might be copied from default Windows 2000 sounds: Shutdown, Log On, Log Off, Balloon, Navigate
* Other missing sounds: Admin Access (might be copied from Warning)
* Suggested file name: `Windows-Pocket-PC-2000.ths`
* Suggested icon:
Windows2000

### `Windows XP Aquarium.ths`
* Missing sounds that might be copied from default Windows XP sounds: Log On, Log Off, USB Connect/Remove/Error, Balloon, Navigate
* Other missing sounds: Admin Access (might be copied from Warning)
* Suggested file name: `Windows-XP-Aquarium.ths`
* Suggested icon:
Scheme

### `Windows XP Da Vinci.ths`
* Missing sounds that might be copied from default Windows XP sounds: Log On, Log Off, USB Connect/Remove/Error, Balloon, Navigate
* Other missing sounds: Admin Access (might be copied from Warning)
* Suggested file name: `Windows-XP-Da-Vinci.ths`
* Suggested icon:
Scheme

### `Windows XP Space.ths`
* Missing sounds that might be copied from default Windows XP sounds: Log On, Log Off, USB Connect/Remove/Error, Balloon, Navigate
* Other missing sounds: Admin Access (might be copied from Warning)
* Suggested file name: `Windows-XP-Space.ths`
* Suggested icon:
Scheme

### `Windows XP build 2481 sounds.ths`
* Other missing sounds: Admin Access (might be copied from Warning)
* Suggested file name: `Windows-XP-Build-2481.ths`
* Suggested icon:
Scheme

### `Windows XP nature.ths`
* Missing sounds that might be copied from default Windows XP sounds: Log On, Log Off, USB Connect/Remove/Error, Balloon, Navigate
* Other missing sounds: Admin Access (might be copied from Warning)
* Suggested file name: `Windows-XP-Nature.ths`
* Suggested icon:
Scheme

### `Windows XP-Vista remix.ths`
* Suggested file name: `Windows-XP-Vista-Mix.ths`
* Suggested author: `Microsoft Corporation / Sergiaws`

### `XP Tribute by Sergiaws.ths`
* Sound events Shutdown and Question have a slight delay before playing. Could be nice to edit it out, but could also be nice to keep it for preservation if that's official .wav files from Microsoft.
* Suggested file name: `Windows-XP-Tribute-Sergiaws.ths`
* Suggested icon:
Scheme

### `celestial 2.0.ths`
* Missing sounds that might be nice to populate: USB Error, Navigate, Recycle Bin
* **Leftover Admin Access sound from Windows 7 (should be removed,** might be replaced by Warning.wav)
* Suggested file name: `Linux-Celestial-2.0.ths`
* Suggested About: Some context about that scheme (**at least remove https://www.microsoft.com/**)
* Suggested icon:
Tux

### `celestial 2.1.ths`
* Missing sounds that might be nice to populate: Question, Navigate, Recycle Bin
* **Leftover Admin Access sound from Windows 7 (should be removed,** might be replaced by Warning.wav)
* Suggested file name: `Linux-Celestial-2.1.ths`
* Suggested Name: Celestial Linux **2.1**
* Suggested About: Some context about that scheme (**at least remove https://www.microsoft.com/**)
* Suggested icon:
Tux

### `jungle.ths`
* Missing sounds that might be copied from default Windows 98 or 2000 sounds: Log On, Log Off, USB Connect/Remove/Error, Balloon, Navigate
* Other missing sounds: Admin Access (might be copied from Warning)
* Suggested file name: `Windows-9x-Jungle.ths`
* Suggested Name: `Underwater`
* Suggested icon:
win98

**Comment by Sergiaws** [comment]
There's an interesting situation.
1. Admin access sound event is not pressent In old versions of Windows (XP and older).
2. Never noticed the thing about icons, I'm totally blind!
3. Regarding Ubuntu classic I named it this way cause that scheme is pressent in most popular classic versions of Ubuntu.
4. Vista Thinker sounds are official wav files, extracted from my Windows Vista pc.
5. Regarding Windows 10 build 10074, don't know why these sounds are different. Sometimes Microsoft releases a sound scheme but then they decide to replace it.
6. As I told, admin access is only pressent in Windows Vista and newer. Balloon and USB related sounds are only pressent in XP and newer. USB sound events in Windows 2000 where added by another person, so I'm not sure if these events are pressent in a normal Windows 2000 install. Windows CE/Phone/similar and older Windows than XP don't have the USB related events.
7. The scheme I created with Windows 8, 10 and 11 remix includes some Windows 8 sounds, Windows 10 (build 10074) sounds, normal Windows 10 sounds and some Windows 11 sounds.
8. Windows 98 plus! Windows 98.ths scheme came from a Windows 98 Plus Scheme, so original Windows 98 sounds and this Microsoft Plus! theme are two things totally different.
9. Windows 9x-2000 remix.ths: This scheme uses the Windows 95 startup sound, which sounds like it was played on a recorder. I did this scheme cause I wanted to create a Windows 95 sound scheme but it would lack a lot of events, so I decided to make a remix where I used Windows 95 startup sound, some other sounds which came from Windows 95 Plus/98/2000. The question sound which is too long is the Windows 98 startup sound.
10. Regarding my scheme XP tribute, these sounds with delay came from XP Tour songs, maybe someone more experienced with audio editing would have better luck. Shutdown and question sounds are from a non-official sounds which were included on a package called The Os sound Kit.
11. Regarding the Celestial Sound schemes, can't find more info about it. Just found it on the OsSoundKit pac, with other Linux scheme. Only thing that I know is that the scheme was created between 2007 and 2009, cause it included some Windows Vista Ultimate extra's sounds. So the situation is the same as Windows scheme which you named Windows Longhorn, these sounds never appeared on any version of Windows. Another interesting fact is that the Celestial Startup/Shutdown sounds where considered as the newer Windows NT 7.0 / Windows 7 sounds. You can see that on the following video. https://www.youtube.com/watch?v=mir19Behzfk

**Comment by ORelio** [comment]
> Admin access sound event is not pressent In old versions of Windows (XP and older).

Indeed. On the sound schemes I made, I tried to use anothet sound to fill in. For instance on the XP sound scheme, the Popup Blocked sound from Internet Explorer 6 works surprisingly well for UAC prompt.

However, I understand that there's a tradeoff between being faithful to the old scheme / preservation and trying to fill in to make a more complete / enjoyable sound pack.

So I'll let you decide what you prefer to do on the schemes you are submitting.

> Never noticed the thing about icons, I'm totally blind!

Icons are totally optionnal, but more pleasant. Feel free to omit the icon if you don't want one or don't know what to use.

> Regarding Ubuntu classic I named it this way cause that scheme is pressent in most popular classic versions of Ubuntu.

Okay. Let's keep it. On a side note, as I've seen a few ocurrences of "pressent" in sound scheme description: you might want to be aware that it should be spelled "present" (no offense intended, my English is not perfect either).

> Vista Thinker sounds are official wav files, extracted from my Windows Vista pc.

Okay. Let's not touch anything.
(Is it Tinker or Thinker?)

> Regarding Windows 10 build 10074, don't know why these sounds are different. Sometimes Microsoft releases a sound scheme but then they decide to replace it.

Okay.

> As I told, admin access is only pressent in Windows Vista and newer. Balloon and USB related sounds are only pressent in XP and newer. USB sound events in Windows 2000 where added by another person, so I'm not sure if these events are pressent in a normal Windows 2000 install. Windows CE/Phone/similar and older Windows than XP don't have the USB related events.

You can try to fill in if it seems appropriate, or not to remain faithful to the original OS. Your choice.

> The scheme I created with Windows 8, 10 and 11 remix includes some Windows 8 sounds, Windows 10 (build 10074) sounds, normal Windows 10 sounds and some Windows 11 sounds.

Okay

> Windows 98 plus! Windows 98.ths scheme came from a Windows 98 Plus Scheme, so original Windows 98 sounds and this Microsoft Plus! theme are two things totally different.

Okay

> Windows 9x-2000 remix.ths: This scheme uses the Windows 95 startup sound, which sounds like it was played on a recorder. I did this scheme cause I wanted to create a Windows 95 sound scheme but it would lack a lot of events, so I decided to make a remix where I used Windows 95 startup sound, some other sounds which came from Windows 95 Plus/98/2000. The question sound which is too long is the Windows 98 startup sound.

Okay

> Regarding my scheme XP tribute, these sounds with delay came from XP Tour songs, maybe someone more experienced with audio editing would have better luck. Shutdown and question sounds are from a non-official sounds which were included on a package called The Os sound Kit.

I could try editing them for you if you want, but if they are original files from Microsoft, you can keep them as is.

> Regarding the Celestial Sound schemes, can't find more info about it. Just found it on the OsSoundKit pac, with other Linux scheme. Only thing that I know is that the scheme was created between 2007 and 2009, cause it included some Windows Vista Ultimate extra's sounds. So the situation is the same as Windows scheme which you named Windows Longhorn, these sounds never appeared on any version of Windows. Another interesting fact is that the Celestial Startup/Shutdown sounds where considered as the newer Windows NT 7.0 / Windows 7 sounds. You can see that on the following video. https://www.youtube.com/watch?v=mir19Behzfk

Thanks anyway for this. It's a nice scheme!

**Review by ORelio — APPROVED** [review]

**Pull request merged**
